### ISSUE TITLE
Artifact deployed to Maven Central depends on parent - which isn't

### ISSUE THREAD

**Issue by kemitix** [atp-mipt/ljv#15]
The artifact `org.atp-fivt:ljv:1.01` uses `org.atp-fivt:ljv-parent:${revision}` as its `parent`, but that artifact is not deployed to Maven Central.

This causes attempts to use `ljv` on a machine that hasn't built the package from source to fail with the error:

`Could not resolve dependencies for project net.kemitix.binder:binder-app:jar:1.0.0-SNAPSHOT: Failed to collect dependencies at org.atp-fivt:ljv:jar:1.01: Failed to read artifact descriptor for org.atp-fivt:ljv:jar:1.01: Failure to find org.atp-fivt:ljv-parent:pom:${revision} in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced`.

**Comment by OrangeFlag** [comment]
Thanks for the issue!
We'll fix this soon, meanwhile you can create the LJV locally as a workaround.

**Comment by inponomarev** [comment]
Hi @kemitix , please try `org.atp-fivt:ljv:1.02` (at the time I'm writing this it's released, but not yet indexed by Maven Central Search). We'll be happy if you tell us if it works )

**Comment by inponomarev** [comment]
fixed in 1.02
